### ISSUE TITLE
从 Jekyll 迁移的日期格式问题

### ISSUE THREAD

**Issue by wogong** [InkProject/ink#1]
post 的 metadata 这里，Jekyll 的 date 定义形式如 2015-04-12，没有时分秒字段，在使用 `ink convert _post` 迁移到 ink 后，无法渲染页面。报如下错误：

    [31;1mparsing time "2012-08-18" as "2006-01-02 15:04:05": cannot parse "" as "15"
    [0m

手动添加时分秒字段如 `22:17:16` 可以解决问题，希望提供兼容功能。谢谢。:)

**Comment by imeoer** [comment]
@wogong 非常感谢反馈，已fix
转换将会追加00:00:00时间，新增转换过程日志，可从主页下载最新版本 :)
