### ISSUE TITLE
Are you interested in adding support for Classless themes?

### ISSUE THREAD

**Issue by fiatjaf** [InkProject/ink#101]
See more information on https://classless.alhur.es/.

The basic idea is that the same HTML template/layout could support many different themes by just changing one CSS tag. The [HTML structure](https://github.com/fiatjaf/classless/blob/master/explained-structure.html) is very simple and straightforward and standards-compliant. The themes support basically _article pages_ and _list pages_, like what Ink already supports.

https://classless.alhur.es/themes/ has already some themes ported from other blog engines that work very well, if you wanna take a look.

**Comment by w568w** [comment]
It looks really nice, but we are not going to work on it recently. 

p.s. If someone manages to port it to Ink theme, we are happy to accept a pull request any time.

**Comment by fiatjaf** [comment]
This was 5 years ago!

**Comment by w568w** [comment]
Yeah, Ink has been essentially out of maintenance since late 2017... But now it looks promising to come back to life again. 😸
