### ISSUE TITLE
移动端页面Markdown显示存在问题

### ISSUE THREAD

**Issue by by-syk** [InkProject/ink#102]
移动端页面 Markdown 显示存在问题，部分格式无法正确显示。请教在移动端强行使用电脑版网页该如何修改配置参数？

**Comment by w568w** [comment]
你需要自行修改主题目录下的相关文件（如 `_head.html`）。这些链接可能会帮助你：

1. https://stackoverflow.com/questions/58357819/how-can-i-force-desktop-view-on-a-mobile-device-from-my-html-or-javascript-code
2. https://stackoverflow.com/questions/31334481/how-to-force-desktop-view-on-mobile-devices-bootstrap
3. https://css-tricks.com/user-opt-out-responsive-design/
