### ISSUE TITLE
隐藏问题

### ISSUE THREAD

**Issue by Aronlele** [InkProject/ink#108]
隐藏掉的文章，通过打开同一标签页内文章，即可访问到

**Comment by imeoer** [comment]
@Aronlele 是个问题，会在下个版本中修复，非常感谢。

**Comment by Aronlele** [comment]
感谢辛苦

imeoer <notifications@github.com> 于2018年8月24日周五 上午9:45写道：

**Comment by KnectBis** [comment]
类似问题：在文章底部 前一篇 后一篇 会显示 隐藏的文章
