### ISSUE TITLE
site下新建变量后会导致文章生成错误

### ISSUE THREAD

**Issue by akkuman** [InkProject/ink#112]
文档中提到

> 在source目录下创建的任意.html文件将被复制，这些文件中可引用config.yml中site字段下的所有变量。

![](http://ww1.sinaimg.cn/large/c0264382gy1fuigdcwpsfj20kw03974g.jpg)

不过我在site下新建变量后会导致文章生成错误

**Comment by imeoer** [comment]
@akkuman 暂时不支持自定义变量，只支持 `site` 下官方定义的变量哈。
