### ISSUE TITLE
MarkDown解析错误

### ISSUE THREAD

**Issue by hupong** [InkProject/ink#113]
**Describe the bug**
Markdown解析序号标记的多个链接的时候，序号为[1]的链接没有解析。
测试用例见附件:
[source.zip](https://github.com/InkProject/ink/files/2380679/source.zip)

如附件中的1.html的第33行的“*   [电子书资源总汇][1]  ” 中的[1]没有解析为相应的链接，而其它的则解析正常

**Comment by w568w** [comment]
在目前版本中，该问题已经修复，建议关闭。@imeoer

**Comment by imeoer** [comment]
@w568w 多谢，先关闭了
