### ISSUE TITLE
希望将链接解析为在新页面打开

### ISSUE THREAD

**Issue by imKnect** [InkProject/ink#115]
如题，目前链接似乎都是在本页打开，非常不便。

很感谢作者的贡献~ 纸小墨很好用 ~

[Knect的博客](https://iKnect.me)

**Comment by imeoer** [comment]
@KnectBis 因为大部分链接都是站内链接。可以使用 Command / Ctrl 键以新页面方式打开。

**Comment by LeeKwanTo** [comment]
> @KnectBis 因为大部分链接都是站内链接。可以使用 Command / Ctrl 键以新页面方式打开。



> 如题，目前链接似乎都是在本页打开，非常不便。
> 
> 很感谢作者的贡献~ 纸小墨很好用 ~
> 
> [Knect的博客](https://iKnect.me)

可以在主题里的文章链接后面添加 target="_blank"，使链接在新页面

**Comment by w568w** [comment]
这个问题不必由纸小墨解决。现在有三种方式完成：

1. **全局生效**：在主题的 head （通常是 `_head.html`）中添加 `<base target="_blank">`，以后博客内的所有链接都会变为新页面打开；
2. **页面级生效**：在需要生效的文章中添加以下部分：
    ```html
    <script type="text/javascript">
        $(function () { $(document.links).attr('target', '_blank') })
    </script>
    ```
    如果需要多次使用，可以保存为 `.js` 脚本引入；
3. **单句生效**：直接使用 `<a href="http://example.com/" target="_blank">Hello, world!</a>` 即可。
