### ISSUE TITLE
请问 root: Website Root Path 为什么无效？

### ISSUE THREAD

**Issue by iblackly** [InkProject/ink#12]
config.yml 中的 root: /blog
修改后生成无效呢？
生成的html 内没有加入root的参数
结果还是这样的
<link rel="stylesheet" href="/css/index.css">

是我没明白怎么用还是怎么回事？
大神辛苦了~

**Comment by imeoer** [comment]
若用`ink preview`命令，生成的html中是没有/blog前缀的，是为了能在本地预览
用`ink build`命令，生成的应该是有前缀的 :)

**Comment by iblackly** [comment]
哈哈~解决了~看来是我不会用~噗~
谢谢大神~辛苦了~
