### ISSUE TITLE
Ink doesn't build 

### ISSUE THREAD

**Issue by dignissimus** [InkProject/ink#124]
Ink fails to build since it depends on `oper` and [the project's github repository](https://github.com/taadis/oper) has since been deleted.

To reproduce this you can clone the ink repository and attempt to build it by running Running `go get https://github.com/inkproject/ink` or by using these commands
```bash
git clone https://github.com/inkproject/ink
cd ink
go build
```
The `go build` command outputs the following error

```C
serve.go:11:2: cannot find package "github.com/taadis/oper" in any of:
	/usr/lib/go/src/github.com/taadis/oper (from $GOROOT)
	/home/sam/go/src/github.com/taadis/oper (from $GOPATH)
```

This has been tested on Arch Linux with the `5.8.9-arch2-1` kernel and also MacOS however the build will fail on all operating systems since the issue occurs at the Go level.

I've already fixed the issue locally so I'll be submitting a pull request very soon

**Comment by imeoer** [comment]
Fixed by @dignissimus, thanks!
