### ISSUE TITLE
Improve site previews

### ISSUE THREAD

**Issue by dignissimus** [InkProject/ink#126]
Ink has a basic site preview that always shows the logo for the site, however it would be nice to show an image specific to the article and to also show the name of the article as well as a subtitle. Alongside the normal options, two new options will be added that will work the same as the other options

```R
image: /images/image.png
subtitle: Example subtitle
```

I've already made a commit adding these features and I'll be submitting a pull request very soon.

**Comment by imeoer** [comment]
Thanks, @dignissimus, I'm so happy to see the tiny but useful improvement, PR merged ;) .

**Comment by dignissimus** [comment]
You're welcome! It's no problem at all
