### ISSUE TITLE
Remove comment section from about page

### ISSUE THREAD

**Issue by qwang07** [InkProject/ink#130]
**Is your feature request related to a problem? Please describe.**
There is comment section in about page. It should be removed.

**Describe the solution you'd like**
Create new page named `about.html` in `theme` folder. Because it always used for personal blog. That means most articles are written by the ourselves. I think one common `about.html` page is more make sense than different authors in `config.yml`. I also suggest new variable `originalURL` (if the article is reproduce from somewhere else) for `article.md`, and `author` can be a `string` which is original author of that article.

**Comment by w568w** [comment]
Just to make sure I do not get you wrong, you want to **(a)** remove the comment section in the about page, **(b)** use a single customized about page, and **(c)** create an external link to the originial author. 

For (a), you could complete it easily by wrapping the comment code with conditional statements in the script of `_comment.html`, e.g. `if(window.location.pathname.contains("about"))`.

For (b), I suppose that we *do* support plain HTML files. Just put them in your source directory with the same filenames (e.g. `about.me.html`), and they will be copied to the public directory at bulid.

For (c), there could be some more "elegant" ways to accomplish this. For example, we are going to support article-level user-defined variables in the future. Please tell if you have other good ideas.

**Comment by w568w** [comment]
Close due to stale.
