### ISSUE TITLE
chole.io still part of this project?

### ISSUE THREAD

**Issue by bronger** [InkProject/ink#133]
Ink refers to chole.io at various places.  This doesn’t seem correct to me.

**Comment by imeoer** [comment]
No, this domain has been deprecated.

**Comment by at15** [comment]
I think we should update the link in footer template since the chole domain now points to well ... whatever it is

https://github.com/InkProject/ink/blob/cac8aab4d83cc150fcd041442c481f14fc88675d/template/theme/_footer.html#L8
