### ISSUE TITLE
寻找新的维护者？

### ISSUE THREAD

**Issue by w568w** [InkProject/ink#135]
👋你好开发者，看起来项目已经很久没有更新过了，我猜想您已经没有精力继续维护项目了。

作为一个纸小墨[五年老用户](https://api.github.com/repos/w568w/w568w.github.io)，之前还提交过[主题](https://github.com/InkProject/ink/issues/123)，看到这个项目死掉真的很惋惜……😕

请问您是否在寻找新的维护者？我有 Rust 和前端开发的基础，最近恰好在学习 Go，我可以在接下来的一段时间里帮助继续维护项目。如果您觉得合适的话，可以留下邮箱联系，或者直接发信给[我的邮箱](https://github.com/w568w)。

**Comment by imeoer** [comment]
@w568w 您好，确实精力不足疏于维护，如果愿意的话，我把你加为 mantainer，我也可以负责 code review

**Comment by w568w** [comment]
> 您好，确实精力不足疏于维护，如果愿意的话，我把你加为 mantainer，我也可以负责 code review

刚刚提交了 PR #136 ，您可以先 Review 一下代码质量后再决定添加权限🚀

**Comment by w568w** [comment]
Hi @imeoer，我想知道您是否介意把我添加为相应权限角色，以便于我分配和解决相关 issues？

**Comment by imeoer** [comment]
Hi @w568w 已经发送邀请，请查收同意。
