### ISSUE TITLE
[Build] Nightly build

### ISSUE THREAD

**Issue by w568w** [InkProject/ink#140]
> Maybe we can publish the release binary using github action automatically, and update the [doc](https://github.com/InkProject/ink#quick-start).

_Originally posted by @imeoer in https://github.com/InkProject/ink/issues/139#issuecomment-1420361461_
            

Use GitHub Action to publish a rolling release version of Ink.

**Comment by imeoer** [comment]
@w568w Maybe we can follow the [semver](https://semver.org/) spec, and trigger the release action when pushing a new git tag (v0.x.x), example: https://github.com/dragonflyoss/image-service/blob/master/.github/workflows/release.yml
