### ISSUE TITLE
tag 下超过10篇文章时，翻页按钮链接出错

### ISSUE THREAD

**Issue by JPLiu** [InkProject/ink#148]
当同一个 tag 下的文章超过10篇时，会触发 tag 的分页，但是在 tag 的分页页面中，下一页/上一页按钮的链接存在问题。

下图示例的下一页按钮中：
正常情况下应当为：
`<a class="next" href="/tag/Double%20Commander/page2.html">下一页</a>`

但默认生成的结果为：
`<a class="next" href="/tag%5cDouble%20Commander%5cpage2.html">下一页</a>`
生成的结果在 push 后，点击下一页时，因无法找到对应链接，会报错。

![图片](https://github.com/InkProject/ink/assets/13379952/7ba05106-1426-470b-957e-9fb308dc7a3c)

**Comment by w568w** [comment]
稍后会回来尝试复现这个问题。在此期间，你可以提供一个 [最小可复现样例](https://stackoverflow.com/help/minimal-reproducible-example) 吗？

**Comment by JPLiu** [comment]
此回复附件为一个可复现的 Source 示例，仅包含名为 Test 的标签下的12篇文章。

补充：实测在使用 Preview 的情况下，生成的链接有问题但可成功点击（测试浏览器为 Firefox），但 Publish 到 GitHub 之后点击则 github-pages 报错。

![图片](https://github.com/InkProject/ink/assets/13379952/bb692245-cf08-435c-85fe-3829a693c45f)


[source.zip](https://github.com/InkProject/ink/files/11786380/source.zip)

**Comment by w568w** [comment]
抱歉这么迟才回复，上周比较忙。

你现在使用的 Ink 是什么版本？如果是较久之前获取的版本，请尝试 [每日构建](https://github.com/InkProject/ink/releases/tag/nightly) 版本，看看能否复现该问题。

在默认主题和当前的构建版本下，我未能复现你展示的问题。`ink build` 后 `tag/Test/index.html` 内容截取如下：

```html
<section class="page-nav">
    <span class="nav">1 / 2</span>
    <a class="next" href="/tag/Test/page2.html">下一页 ▶</a>
</section>
```
我猜想这个问题已在 <https://github.com/w568w/inkstone/commit/be7247dcbbd8426000e4b9920da3e4814b94d1eb> 中修复。

**Comment by JPLiu** [comment]
实测 Nightly 已修复此问题，谢谢。
