### ISSUE TITLE
似乎没法使用Markdown的注释？

### ISSUE THREAD

**Issue by Skimige** [InkProject/ink#21]
喂猫是English……算了不管了我就用中文写好了

嘛，举个例子：

``` Markdown
*等身的作业* [^HW]

[^HW]: 引用自《纪念伏尔泰逝世一百周年的演说》
```

_等身的作业_ [^HW](引用自《纪念伏尔泰逝世一百周年的演说》)

**Comment by Skimige** [comment]
Gayhub的预览抽风……我没办法。反正意思就是点了那个^HW 其实是小1 会跳到文章最下的注释part。

**Comment by imeoer** [comment]
@Skimige 注意到啦，目前ink的Markdown支持依赖 [blackfriday](https://github.com/russross/blackfriday) 精力有限，慢慢改善，这个issue先开着 _(:з」∠)_
