### ISSUE TITLE
linux ink preview error

### ISSUE THREAD

**Issue by lhfx** [InkProject/ink#23]
root@OpenWrt:/myblog/ink_linux_386# ./ink preview
./ink: line 1: syntax error: unexpected "("

**Comment by imeoer** [comment]
strange, what's the linux distro you are using?

**Comment by lhfx** [comment]
TP-Link  WR720N with OpenWrt .

**Comment by imeoer** [comment]
:( No test on this platform, may be you need build from source:
https://github.com/InkProject/ink#build-from-source

**Comment by lhfx** [comment]
I have already migrated to the aws,tks = =b

**Comment by imeoer** [comment]
all right.
