### ISSUE TITLE
Preview的时候出现红色错误提示

### ISSUE THREAD

**Issue by ArKurt** [InkProject/ink#24]
Parse config.yml failed, please specify a valid path

无法预览

**Comment by imeoer** [comment]
ink preview需要指定blog所在目录，也就是config.yml所在目录。
如果是当前目录，就是：ink preview或ink preview .
如果是/to/path目录，就是：ink preview /to/path

**Comment by ArKurt** [comment]
多谢！这里已经解决啦！
