### ISSUE TITLE
we can see the passwd

### ISSUE THREAD

**Issue by lhfx** [InkProject/ink#25]
http://XXX.com/..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2Fetc%2Fpasswd

root:x:0:0:root:/root:/bin/bash
...
...
...
ubuntu:x:1000:1000:Ubuntu:/home/ubuntu:/bin/bash

**Comment by imeoer** [comment]
@lhfx what's the meaning?

**Comment by lhfx** [comment]
噗。。
就是在linux环境中，ink程序要使用80端口，只能以root用户运行才可以。
然后ink就有了访问系统文件的权限，在浏览器遍历目录就可以访问系统文件了，比如我上面列到的用户列表文件，对应的实际文件就是/etc/passwd。
目前linux有个解决方案，就是ink用当前用户启动1024-65535之间的端口，不需要root权限就可以，然后在防火墙里设置端口转发到80上。
然面ink程序里面我猜可以限制目录访问的范围吧，不让他无限的../../../../

**Comment by imeoer** [comment]
嗯，访问80端口需要有root权限，要是信任这个程序就给呗，或者做端口转发。
像Nginx, Apache一般是用root权限启动主进程，但应该只用来做监听和调度，然后创建一般权限的worker进程。
还有个方案是使用Linux 2.6.11以上的`setcap`来设置某个程序的权限，比如用`sudo setcap 'cap_net_bind_service=-ep' ./ink`，这样ink只有绑定80端口的权限而没有访问系统文件的权限了。

**Comment by imeoer** [comment]
ink更新了新版本(2015-11-06)哦，已发布到主页，把前端构建从gulp换成了webpack，合并压缩文件，改善了主题和排版。

**Comment by imeoer** [comment]
@lhfx 提交了fix的commit，下次release会更新至官网 :)

**Comment by lhfx** [comment]
加油~~~233333

**Comment by imeoer** [comment]
感谢，已限制url只能访问public目录 :)
