### ISSUE TITLE
关于引用路径

### ISSUE THREAD

**Issue by Nigh** [InkProject/ink#28]
由于目前生成的html中使用的引用全部都是绝对路径，导致页面只有在根目录下才能正常访问。执行替换`"/`为`"./`后（暴力替换为相对路径）才可以部分正常访问。

问是否能将所有本地引用路径改为相对路径？

**Comment by imeoer** [comment]
目前是支持相对路径的，config.yml中的root字段用于配置路径前缀。比如root设置为/blog，则所有-/的写法都会被替换为/blog/。 :)

**Comment by Nigh** [comment]
thx, i'll try it.
