### ISSUE TITLE
当source里有较多文件的时候，在util.go里的Copy*函数会报错open <path/to/filename>: too many open files

### ISSUE THREAD

**Issue by gaocegege** [InkProject/ink#3]
本来想自行解决，发现自己不会编译项目Orz

**Comment by imeoer** [comment]
@gaocegege 是最新版本(2015-04-12)吗？上个版本有这个问题，已fix. :)
如果文件过多，可设置`ulimit -n 65535`

**Comment by gaocegege** [comment]
@imeoer 是Beta 2015-04-11版本。。

**Comment by imeoer** [comment]
@gaocegege 感谢测试，如果遇到其他问题可以继续提issue :)

**Comment by gaocegege** [comment]
:ok:

**Comment by imeoer** [comment]
@gaocegege 安装好Go环境，在ink repo目录下执行`go build`就能编译了

**Comment by ShionRyuu** [comment]
> 如果文件过多，可设置ulimit -n 65535

@imeoer goroutines同时打开的文件过多，建议使用chan+goroutines来避免，而不是使用ulimit -n。另外，建议使用go fmt格式化一下代码。

**Comment by imeoer** [comment]
@ShionRyuu 的意思是用chan等待一部分goroutine完成，再跑下一组？
感谢建议，代码会做整理。也欢迎参与，可以提PR或加入这个项目 :)

**Comment by ShionRyuu** [comment]
@imeoer 
1. 生成固定数量的go routine，将所有要复制的文件的路径发送到channel中（可以考虑请求封装为一个对象），go routine从channel中获取文件路径（对象）并复制（执行相应操作）。
2. 将有缓冲的channel当作信号量
3. 其它

**Comment by imeoer** [comment]
@ShionRyuu 我的理解是2比1的并发性更好，一旦有可打开文件数就执行复制，是这样吧

**Comment by ShionRyuu** [comment]
@imeoer 一样的，都是限制同时打开文件的go routine的数量。
