### ISSUE TITLE
关于inkpaper的3个问题请教

### ISSUE THREAD

**Issue by Yuki-Judai** [InkProject/ink#30]
你好，猫叔，开发和维护辛苦了。我这里有3个关于inkpaper的问题想请教一下。

1、可以自己把评论换成多说吗？

2、作为静态博客，评论的数据是存储在哪里的呢？

3、是不是现在由markdown转成html，还不支持代码高亮呢？（我试了下Objective-C，似乎是还没有代码高亮）。还有是不是还不支持markdown的大纲功能呢？（[TOC]）

**Comment by imeoer** [comment]
@Yuki-Judai 
1. 能换成任何其他评论插件，按各自配置做就可以
2. 数据是存储在提供评论插件的平台里的，InkPaper不存储数据
3. TOC暂不支持（目前依赖于三方的Markdown解析库[Blackfriday](https://github.com/russross/blackfriday)），支持常用语言的代码高亮，OC的高亮前缀：
```
``` objective-c
```

**Comment by Yuki-Judai** [comment]
嗯，了解了。多谢解答。:-) 祝项目顺利。
