### ISSUE TITLE
关于替换评论插件

### ISSUE THREAD

**Issue by Yuki-Judai** [InkProject/ink#31]
你好，猫叔。

关于替换评论插件的问题想咨询下你。

我发现在生成的文章html最后，都有这一段代码：

```javascript
    <script type="text/javascript">
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//somebody.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
```

要替换评论插件，是不是要删除所有文章html的这段代码呢？那么，我想咨询下：

1. 生成这段代码的 go 文件在哪里呢？（在build.go里好像没有）。

2. 如果我想用 多说 评论插件，是不是需要修改build代码，让程序自动在每个文章html加入调用这个插件的代码呢？

3. 如果需要加入代码，那能否提示一下代码该怎么写呢？

（抱歉，问题比较小白。打扰了。）

**Comment by imeoer** [comment]
这段代码就在`theme/article.html`的末尾，它是所有文章页面的模板文件，只需要按照多说的用法替换掉这段代码，然后重新`ink build`就可以了。 :)

**Comment by imeoer** [comment]
抱歉现在文档还不够完善，后面会更新的详细些。 :)

**Comment by Yuki-Judai** [comment]
哦哦，多谢猫叔解答。文档没关系，慢慢来。猫叔应该很忙吧。维护代码不容易。祝工作顺利。:-)

**Comment by imeoer** [comment]
嗯，只要有空就会继续维护的。
