### ISSUE TITLE
Disable disqus

### ISSUE THREAD

**Issue by crane-may** [InkProject/ink#32]
我没有看到官方提供的关掉 disqus 的方法，如果注释掉的话会向 '.disqus.com' 发起个无用的请求并且被 503。

如果有跟我一样强迫症的朋友可以用注入方式解决 503 的问题
```
config.yml:
  ...
  disqus: '; return; '
  ...
```

**Comment by imeoer** [comment]
感谢发现这个问题 :) 也可以在`article.html`模板中删除最后的disqus插件脚本；
已提交最新commit，在`disqus`选项置空时，不追加那段脚本，将在下次release发布。
