### ISSUE TITLE
关于theme设置

### ISSUE THREAD

**Issue by Nigh** [InkProject/ink#33]
因为每次更改主题都需要更改配置文件中的site中的theme字段和build中的copy段，如果主题较多，挑选主题的时候，每次需要一个一个改，会比较麻烦。
希望更换主题的时候只需要更改一处就好。
可以考虑把

    copy:
        - theme/css
        - theme/js
        - theme/favicon.ico
        - theme/robots.txt

这段直接放到主题里面。

**Comment by imeoer** [comment]
@Nigh 了解，的确应该放在theme中，新增个`config.yml`，放置copy和lang字段，会在下次版本中发布 ;)

**Comment by imeoer** [comment]
@Nigh 最新commit也已支持 :)

**Comment by Nigh** [comment]
@imeoer nice work.希望尽快更新README.

**Comment by imeoer** [comment]
@Nigh 目前在issue中标记为`next`的表示已提交了commit，会在下次release时一起发布，同时也会更新文档
