### ISSUE TITLE
improvement on copying files

### ISSUE THREAD

**Issue by Nigh** [InkProject/ink#34]
希望能添加这样的功能：在article中增加copy配置字段，生成html时将对应文件复制至html的相同目录下。这样可以方便管理本地资源，提供一个可以在同一个article里面把资源跟markdown放一起的管理方法。

我现在的目录结构是这样的：`blog/source/{year}/{month}/{article.name}/`，每篇文章我会建立一个目录，然后把md和本地图片什么的都放到这个目录里面。

**Comment by imeoer** [comment]
@Nigh 已提交最新commit，现在config.yml中的`copy`字段支持模式匹配，例如`source/*/*/res`可以匹配`source/abc/def/res`，`def`文件夹下的markdown写`-/res/image.jpg`就可以引用`source/abc/def/res/image.jpg`了
