### ISSUE TITLE
关于添加自定义配置字段的需求

### ISSUE THREAD

**Issue by Nigh** [InkProject/ink#35]
## 情景
目前使用多说评论系统，模板中需使用一个key来对文章做唯一映射。目前使用.Date勉强可用。但不好维护。

## 需求
希望能够在article中添加一个可以user-define的字段。我便可以自定义一个字段来储存文章的多说评论的key

**Comment by imeoer** [comment]
@Nigh 了解，会支持在配置中自定义变量 :)

**Comment by imeoer** [comment]
@Nigh 已提交最新commit，在config.yml的`Site`下可新增`Config`字段，或在markdown中可新增`Config`字段，这个字段可以是任意类型，比如字符串。;)

**Comment by Nigh** [comment]
@imeoer  如何在模板中引用呢？

**Comment by imeoer** [comment]
@Nigh 比如在markdown写了：
``` yaml
config: foo
```
html中就引用：`{{.Config}}`

如果写：
``` yaml
config:
    foo: bar
```
html中就引用：`{{.Config.foo}}`

**Comment by Nigh** [comment]
已经搞定了。发现go get不会自动覆盖。所以一直报错没有config这个field.. 
更新之后目前一切正常。

**Comment by imeoer** [comment]
@Nigh 嗯 可以用`go get -u`来更新
