### ISSUE TITLE
Support LaTeX Syntax

### ISSUE THREAD

**Issue by imeoer** [InkProject/ink#36]
Solution: http://www.twtccw.com/post/2015/12/20/cmd.html
Prepare for next release, will add to plugin list

**Comment by twtccw** [comment]
Glad to see this solution been accepted, I'm trying to make my blog more easy to use, and would like to help improve InkProject.
很高兴喵叔采纳了这个方案，我也正在尝试让自己的博客支持更多一些的特性，期望能同时帮助喵叔改进「纸小墨」。

**Comment by imeoer** [comment]
@twtccw thanks, any improvement for ink will merge to master, or you can submit pull request ;)
