### ISSUE TITLE
Pages as markdown files

### ISSUE THREAD

**Issue by minimalchaos** [InkProject/ink#39]
why cant pages also be added as markdown files to unify the process instead of html pages

**Comment by imeoer** [comment]
@minimalchaos only .md files processed as a article, html files will replace variables and directly copy to public directory.

**Comment by minimalchaos** [comment]
I was hoping like jekyll if pages could be processed through markdown and using layout in front matter like :
layout : post or layout : page

**Comment by imeoer** [comment]
@minimalchaos oh, sorry, layout is not supported yet, will propose to next milestone. :(
maybe template (like `_header.html`) can be used for your requirement?

**Comment by minimalchaos** [comment]
yes I meant that...I would love contributing to ink. I seem to be loving it after just a few hours of using it.

**Comment by imeoer** [comment]
@minimalchaos cool! Ink is still an young project, any improvement will be very helpful, welcome to be a contributor. ;)

**Comment by minimalchaos** [comment]
I am not a great developer. I'm moving from jekyll to ink. I just hope this project doesn't die out soon. Are you done with the web UI ? I could draw up some sketches.

**Comment by imeoer** [comment]
@minimalchaos I wrote a preview like this:
![image](https://cloud.githubusercontent.com/assets/1524576/12002026/12c46254-ab30-11e5-81b5-ce2e68b3d41c.png)
web UI use webpack, react, redux to build, developing code in `editor` folder. :)

**Comment by minimalchaos** [comment]
npm install does not work
