### ISSUE TITLE
显示的时间能改成分钟或者小时么？

### ISSUE THREAD

**Issue by recall704** [InkProject/ink#4]
-41417秒前 （更新于-41417秒前）
目录页是这样，详细页也是这样。

**Comment by imeoer** [comment]
@recall704 可以贴下md中的date与update字段吗

**Comment by recall704** [comment]
```
title: virtualenv 详解
date: 2015-04-20 19:52:00
update: 2015-04-20 19:52:00
author: me
topic: -/images/example.jpg
tags:
    - virtualenv
preview: virtualenv 是用来创建隔离的 Python 环境的一个工具。
```
我现在看，如果时间是当前时间左右，就会出现。
-39962秒前 （更新于-39962秒前）
过了4天就是 4天前了。

**Comment by imeoer** [comment]
@recall704 抱歉回复较晚，确认是bug，原因是构建环境与浏览器环境时区不一致，稍后在配置中支持显式设置时区. :)

**Comment by imeoer** [comment]
@recall704 新版本(07-04)已修复，在date或update字段后加` +0800`格式，用于表示时区 :)
