### ISSUE TITLE
Can not use symbolic link for source dir

### ISSUE THREAD

**Issue by aminehmida** [InkProject/ink#44]
My source dir is a symbolic link. when I do `./ink publish` it can not see my `.md` files inside source dir

**Comment by aminehmida** [comment]
after some investigation, I found this : [symwalk](https://github.com/facebookgo/symwalk) symbolic link aware filepath walk done by facebook. I hope this can help

**Comment by imeoer** [comment]
@aminehmida Thanks, fix issue using symwalk and in https://github.com/InkProject/ink/commit/fb9088d31fd8f1002125133b6f035a0a41744543
Will build release on next

**Comment by aminehmida** [comment]
Thank you man :+1:
keep up the good work :)
