### ISSUE TITLE
Parsing Time Month Out of Range

### ISSUE THREAD

**Issue by steveny9911** [InkProject/ink#45]
When previewing or building blog with command of `./ink preview`, the error of `parsing time “2016-2-18 14:15:00 -0800”: month out of range` appears.

![screen shot 2016-02-20 at 15 07 36](https://cloud.githubusercontent.com/assets/8460976/13199813/809612e2-d7e4-11e5-9e3d-5ebbbeb26558.png)

The actual time written within the `.md` file
![screen shot 2016-02-20 at 15 07 50](https://cloud.githubusercontent.com/assets/8460976/13199814/8dc188ca-d7e4-11e5-8a41-32fafa42402b.png)

Could this happen because of the wrong time format I wrote?
I have tried with year of 2015 with month 2(February) but it still appears to have the same error of time month out of range.
![screen shot 2016-02-20 at 15 19 27](https://cloud.githubusercontent.com/assets/8460976/13199829/5ebacf04-d7e5-11e5-99e1-4b2157e38a6b.png)

Any year-month-day formatting, with month less than 10 does not work.
![screen shot 2016-02-20 at 15 20 21](https://cloud.githubusercontent.com/assets/8460976/13199832/85fd30f2-d7e5-11e5-8c04-0c39fd1e77d1.png)

If the month value is greater than 10, for any year, there is no error.
Kind of confused by this strange problem but can’t really find any solution.
Much appreciated for helping.

**Comment by imeoer** [comment]
@steveny9911 Should use 02 instead of 2 :)

**Comment by steveny9911** [comment]
(*ﾟ∀ﾟ) Thank you so much!
