### ISSUE TITLE
disqus 应该怎样配置

### ISSUE THREAD

**Issue by lubia** [InkProject/ink#5]
我尝试了disqus的邮箱和用户名，都提示
![image](https://cloud.githubusercontent.com/assets/2741940/8468264/a92f7de2-209c-11e5-9baf-80a42f44dc51.png)

**Comment by imeoer** [comment]
只需要在config.yml里，site -> disqus字段填写账户名，注意填写无误，已测试过自己的账户没有问题，可以看下Disqus给出的 [troubleshooting guide](https://help.disqus.com/customer/portal/articles/472007-i-m-receiving-the-message-%22we-were-unable-to-load-disqus-%22)

**Comment by lubia** [comment]
解决了，需要加入信任domain

**Comment by ArKurt** [comment]
@lubia 我也是同样的问题，加入信任domain还是无法加载……
请问你是怎么解决的？

**Comment by imeoer** [comment]
@ArKurt 可以看下那个 [troubleshooting guide](https://help.disqus.com/customer/portal/articles/472007-i-m-receiving-the-message-%22we-were-unable-to-load-disqus-%22)

**Comment by ArKurt** [comment]
@imeoer 按照那个指南配置了一遍还是不行，我再找找原因
