### ISSUE TITLE
ink publish  err

### ISSUE THREAD

**Issue by aleafboat** [InkProject/ink#53]
[root@weixin-6r7c4 blog]#  ../ink publish 
Building ink-blog-tool-en
Building ink-blog-tool
Copying source/images
Copying theme/bundle
Copying theme/favicon.png
Copying theme/robots.txt

Finished to build in public folder (12.534257ms)
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git

**Comment by shery15** [comment]
It seems no git repository,try remove git command from the `config.yml`
