### ISSUE TITLE
没有适用于amr64的吗？

### ISSUE THREAD

**Issue by joyde68** [InkProject/ink#54]
如题，没有适用于arm64的吗？无奈技术有限尝试自己编译以失败告终。

**Comment by imeoer** [comment]
@joyde68 暂时没有ARM64的编译版，可以在安装好Go环境后执行`go get github.com/InkProject/ink`编译（可能需要梯子），以后会编译ARM64的版本放到官网上哈。

**Comment by imeoer** [comment]
[ink_linux_arm64.tar.gz](https://github.com/InkProject/ink/files/414822/ink_linux_arm64.tar.gz)
Build了个ARM64版本，试试吧。

**Comment by joyde68** [comment]
好哒~  成功了，深表感谢。

**Comment by joyde68** [comment]
@imeoer 谢谢。
