### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by solarhell** [InkProject/ink#61]
For example, i want to add one option in `config.yaml` and add one template in theme folder,
i have already modified `parser.go` 's `SiteConfig` and just can't let my template condition judgement work.
articel.html
```html
{{template "moe" .}}
```
_moe.html
```go
{{if .Site.Moe}}
balabala
{{end}}
```
config.yml
```
site:
    ...
    moe: true
```
parser.go
```
type SiteConfig struct {
	...
	Moe      bool
```

if i run `ink preview`, the console said
```
template: article:148:33: executing "moe" at <.Site.Moe>: can't evaluate field Moe in type main.SiteConfig
```

**Comment by imeoer** [comment]
Hi @solarhell, seems you haven't re-build after modify code.

**Comment by solarhell** [comment]
Thanks for your reply.
BTW,is there some unique key for each article? I want to use this key to distinguish each article so my comment plugin will works well.

**Comment by imeoer** [comment]
@solarhell Haven't yet, I think we can use url path as the unique id of article, how about that?

**Comment by solarhell** [comment]
OK.But this is a compromise cause user may change the article's filename and this will make the article's url change.

**Comment by imeoer** [comment]
@solarhell Seems there is no way to provide a immutable & unique id, unless we specify one in config of article.

**Comment by solarhell** [comment]
OK. If it possible to get article's raw name? Or i will use js to dynamically set.

**Comment by solarhell** [comment]
I used {{ .Title }} to set the unique key.

**Comment by solarhell** [comment]
#62
