### ISSUE TITLE
为毛[TOC]不能用……

### ISSUE THREAD

**Issue by sakurayang** [InkProject/ink#65]
em……由于不太懂go……所以帮不上忙
上网翻了一下文档，发现有以下几个

[简书](http://www.jianshu.com/p/34c92cbd0aaf/)
[atom](https://atom.io/packages/markdown-toc)
[google](https://www.google.com.hk/search?q=markdown+toc)

但是……大多数依赖JS……

**Comment by fofen** [comment]
不支持 [TOC]，是因为 blackfriday （Ink 用的 markdown 解析器）不支持。

**Comment by imeoer** [comment]
@mengqingshare 暂时没有，需要依赖支持哈。
