### ISSUE TITLE
手机上网站首页图片不能随长宽比固定缩放

### ISSUE THREAD

**Issue by itplanes** [InkProject/ink#69]
![snipaste_20170504_224326.jpg](https://ooo.0o0.ooo/2017/05/04/590b3e3fb84ad.jpg) 
引用的同一张图片，在手机上首页图片会变形，
如上图，
但是进入文章页后图片显示却很正常，
![snipaste_20170504_224347.jpg](https://ooo.0o0.ooo/2017/05/04/590b3efe80b83.jpg)
感觉有点影响美观，长宽比固定了更好看。

**Comment by imeoer** [comment]
@itplanes 了解，目前用的是 `background-image` 显示图片，会考虑更新为 `img`标签，也欢迎提 PR 哦。

**Comment by itplanes** [comment]
@imeoer 很喜欢这个程序，不过能力目前不够啊，我会尝试学习怎么解决，很想提交PR。

**Comment by myiq** [comment]
@itplanes 会一点前端的话，就很好解决。你可以将首页`page.html`模板里的 `<div class="cover" style="background-image:url({{.Cover}});"></div>` 替换一下，改成`<img src="{{.Cover}}" title="" alt="">`差不多就行了。别的地方同样适用。不过对齐、大小需要你自己通过css定制一下，就OK了。

**Comment by imeoer** [comment]
@myiq 感谢热心指导，准备更新下这部分，如果有有意也可以提这个 PR 哦。

**Comment by myiq** [comment]
@imeoer 哪里哪里，主要还是因为纸小墨的模板比较浅显易懂，雕虫小技而已。
