### ISSUE TITLE
搜索功能

### ISSUE THREAD

**Issue by bpplpp** [InkProject/ink#70]
最近在移植主题到Ink，首页模板有`{{template "search" .}}`，`_search.html`模板没修改过，但是还是不能搜索。
searchWorker.js 和 index.json 都正常，问题出现在哪里呢？

**Comment by imeoer** [comment]
@bpplpp 可能遇到了浏览器兼容问题，请问浏览器是？以及搜索时浏览器有报错吗？

**Comment by bpplpp** [comment]
chrome浏览器，搜索时没有报错，不介意的话，我把主题基本模板发给你测试一下也行

**Comment by imeoer** [comment]
@bpplpp 嗯，模板有仓库吗？我看看。

**Comment by bpplpp** [comment]
木有github，还是发邮件给你吧

**Comment by imeoer** [comment]
@bpplpp 好像是因为这个主题删除了 `.article-list` 这个 class 导致的。

**Comment by bpplpp** [comment]
确实是这样子，为啥会出现这个问题，是ink里面特定的范围了嘛？

**Comment by imeoer** [comment]
@bpplpp 嗯，在搜索时会操作这个 dom 的。
