### ISSUE TITLE
 感觉不错，特意来感谢一下！

### ISSUE THREAD

**Issue by 1c7** [InkProject/ink#71]
看了下感觉挺好的，官网挺好看的。

之前用 jekyll 做博客那个默认主题不好看，然后随便看了一下第三方的 jekyll 主题也不咋样。
感觉纸小墨不错。
话说官网 http://www.chole.io/ 能放一个 DEMO 吗？
就是搭建出来之后默认样式长什么样子。

谢谢。

**Comment by imeoer** [comment]
@1c7 嘿嘿谢谢，我的博客就是默认样式的 http://www.chole.io/blog/
纸小墨的初衷就是尽可能的让博客简单和可定制，也欢迎提需求和改进哦。

**Comment by 1c7** [comment]
@imeoer  好。没问题~

**Comment by 1c7** [comment]
话说最近我们建了一个小小的微信群，就是
![image](https://user-images.githubusercontent.com/1804755/28422940-1cb2e008-6d9c-11e7-851f-1169cd9ac6c0.png)
就是我们这些 Maker 闲聊这样，你有兴趣吗？
我的话，我做过4个项目：http://1c7.me/project/
最近 yuzhu.me 这个我做的，开始有点 traction 了，我还在加很多新功能。

然后群里最近有个朋友 Product Hunt 拿了300票，这个：https://www.producthunt.com/posts/youtube-classified

你要是有兴趣的话，加下我微信 agoodob，我拉你进去？
不要有啥压力啥的，就是，一群人闲聊这样……
