### ISSUE TITLE
如何在默认主题添加Instantclick啊？

### ISSUE THREAD

**Issue by jiangxu1** [InkProject/ink#72]
我实验了好几次都不行，点击后无法加载正常网页。
这是我用的代码：
`<script src="//huangwuwen.firadio.net/ink/bundle/instantclick.min.js?v=3.1.0" data-no-instant></script>
<script data-no-instant>InstantClick.init();</script>`

**Comment by imeoer** [comment]
@jiangxu1 一般来说脚本加在 `theme/page.html` 或 `theme/article.html` 模板页中 `</body>` 的前面就可以，然后重新 build。

**Comment by jiangxu1** [comment]
感谢，已修改成功。
但是又出现一个问题，我尽可能把所有用到的JS都加上了data-no-instant
但是在加载过程中，网页底部输出年份的JS失效了（© XX 2017），这个该怎么解决啊？？

**Comment by imeoer** [comment]
@jiangxu1 年份部分是JS动态生成的，我想 instant click 是直接加载的静态 html，这部分也许可以参考下
 instant click 文档，等页面加载完成后，再去调用下代码；或者把年份直接写死。

**Comment by jiangxu1** [comment]
好的，已解决，感谢！（就是直接写死。。。）
