### ISSUE TITLE
反馈问题：HTTPS下WebSocket不能正常反馈

### ISSUE THREAD

**Issue by jiangxu1** [InkProject/ink#73]
我在本地生成后上传服务器测试了好几次，都提示![图片](https://ws1.sinaimg.cn/large/c3695bc7gy1fi65p47sojj206w03it8k.jpg)
怎么办啊！我审查元素后又发现WS://的链接是这个JS生成的![图片2](https://ws1.sinaimg.cn/large/c3695bc7gy1fi65qom28lj20e108udfv.jpg)
取消后有多少影响或是怎么变成HTTPS下也可使用的链接呢？

**Comment by jiangxu1** [comment]
图片链接：
1.https://ws1.sinaimg.cn/large/c3695bc7gy1fi65p47sojj206w03it8k.jpg
2.https://ws1.sinaimg.cn/large/c3695bc7gy1fi65qom28lj20e108udfv.jpg

**Comment by imeoer** [comment]
@jiangxu1 `ink preview` 命令是不能用在部署环境的，这个模式下的 websocket 是为了编辑后的实时预览，可以用 `ink serve` 命令，但这个命令还是 beta 状态，考虑到安全和性能，还是强烈推荐用 nginx, apache 之类的服务。

**Comment by jiangxu1** [comment]
前面都明白了，我需要换一个命令。最后的
> 推荐用 nginx, apache 之类的服务。
不明白，不是生成静态HTML后直接上传吗？

**Comment by imeoer** [comment]
@jiangxu1 是的，把静态文件交给其他Web服务托管，`ink` 还不适合直接 serve 静态文件。

**Comment by jiangxu1** [comment]
哦，我明白了。感谢！
