### ISSUE TITLE
推荐的两个主题似乎都没法用的样子

### ISSUE THREAD

**Issue by thomascatlee** [InkProject/ink#75]
ink-pure可能是版本问题，还是旧版的theme格式，作者也很久没更新了。

ink_Werttin这个有新版，不过使用起来也是不行。

出错提示类似下面这样：

D:\work\ink>ink preview
Building about.me.html
Building ink-blog-tool-en.html
Building ink-blog-tool.html
Copying blog\source\images
Copying blog\ink_Werttin\css
Copying blog\ink_Werttin\js
Copying blog\ink_Werttin\favicon.png
Copying blog\ink_Werttin\robots.txt

Finished to build in public folder (60.0147ms)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x40e7ed]

goroutine 1 [running]:
panic(0x7e5400, 0xc0420040d0)
        /usr/lib/go/src/runtime/panic.go:500 +0x1af
main.Watch.func2(0xc0422d4620, 0x17, 0x0, 0x0, 0xa10e00, 0xc042384b70, 0x0, 0x0)

        /home/imeoer/works/golang/src/github.com/InkProject/ink/serve.go:52 +0x2
d
github.com/facebookgo/symwalk.walk.func1(0xc0422d4620, 0x17, 0x0, 0x0, 0xa10e00,
 0xc042384b70, 0x1, 0xc042384b10)
        /home/imeoer/works/golang/src/github.com/facebookgo/symwalk/walk.go:42 +
0x16c
path/filepath.Walk(0xc0423b2060, 0x17, 0xc042384b10, 0x0, 0x0)
        /usr/lib/go/src/path/filepath/path.go:396 +0x92
github.com/facebookgo/symwalk.walk(0xc0423b2060, 0x17, 0xc0423b2060, 0x17, 0x889
558, 0x0, 0x0)
        /home/imeoer/works/golang/src/github.com/facebookgo/symwalk/walk.go:44 +
0xba
github.com/facebookgo/symwalk.Walk(0xc0423b2060, 0x17, 0x889558, 0x0, 0x0)
        /home/imeoer/works/golang/src/github.com/facebookgo/symwalk/walk.go:49 +
0x50
main.Watch()
        /home/imeoer/works/golang/src/github.com/InkProject/ink/serve.go:58 +0x3
05
main.main.func2(0xc042056c80, 0x0, 0xc042056c80)
        /home/imeoer/works/golang/src/github.com/InkProject/ink/main.go:49 +0x41

github.com/codegangsta/cli.HandleAction(0x7d29c0, 0x889570, 0xc042056c80, 0xc042
010700, 0x0)
        /home/imeoer/works/golang/src/github.com/codegangsta/cli/app.go:485 +0xd
b
github.com/codegangsta/cli.Command.Run(0x84ee1f, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0
x85d86b, 0x22, 0x0, ...)
        /home/imeoer/works/golang/src/github.com/codegangsta/cli/command.go:207
+0xb9d
github.com/codegangsta/cli.(*App).Run(0xc0420b4ea0, 0xc042006720, 0x2, 0x2, 0x0,
 0x0)
        /home/imeoer/works/golang/src/github.com/codegangsta/cli/app.go:250 +0x8
19
main.main()
        /home/imeoer/works/golang/src/github.com/InkProject/ink/main.go:83 +0x1e
6

**Comment by imeoer** [comment]
@thomascatlee 看起来可能是主题过旧的问题，试试这个主题呢：https://github.com/myiq/ink-simple

**Comment by thomascatlee** [comment]
myiq的可以~
