### ISSUE TITLE
修改css无效！

### ISSUE THREAD

**Issue by nocmt** [InkProject/ink#77]
我尝试更改～/ink_linux_amd64/blog/theme/source/css/ 里面的css 样式，发现修改后，再度生成的index.css还是原来的！我不知道如何解决。

存在的bug：移动端文章页可左滑动

解决办法：content.css中的“.main .content”增加word-wrap: break-word;

**Comment by shery15** [comment]
修改样式之后 theme 主题文件 需要用 webpack 重新打包发布哟 @nocmt ,

**Comment by nocmt** [comment]
OK，我已经修改好了，请问 “紙小墨寫作工具”制作的如何了？

**Comment by shery15** [comment]
感谢关注，部分功能已经完成，后续功能还在开发中哟。
我们一直在为让写作工具变得更加人性化，友好而努力！
