### ISSUE TITLE
希望添加jiathis分享按钮

### ISSUE THREAD

**Issue by lds2004** [InkProject/ink#80]
如题，官网www.jiathis.com

**Comment by shery15** [comment]
分享功能支持自定义，目前没有指定分享差价

**Comment by lds2004** [comment]
@shery15 那我想实现这个功能，应该吧代码加在那个文件的那一行和那一行之间呢

**Comment by shery15** [comment]
https://github.com/InkProject/ink/blob/0443037365dff576b402b9d6c42b49b2b490cd24/template/theme/article.html#L26 主题文件是可以直接修改的，当然别忘记在修改之后，在主题文件根目录下执行 npm run build 重新构建主题模板
