### ISSUE TITLE
markdown 文件头中的 author 如果不是 ‘me’，则 html 不显示作者

### ISSUE THREAD

**Issue by hiweed** [InkProject/ink#84]
不知道这是 bug 还是 improving requirement，问题是这样的：
在 md 文件的首部：
```
title: "佛教的无常观"
author: 释慧净
```
如上，author 如果不是 me，而是其他内容，则生成的 html 是不包含作者信息的。

我知道 ink 目前应该是单用户 blog 系统，但是如果我想做一个资料库，每篇文章的作者不同，还是有这个需求的呀。

辛苦您了，阿弥陀佛 ^__^

**Comment by shery15** [comment]
https://github.com/shery15/blog/blob/836e1be73973c47d15cca542447d5d45bc2669e6/config.yml#L14 在这里可以定义其他作者哟，支持多用户定义哈

**Comment by hiweed** [comment]
啊，谢谢谢谢，回复这么快，太赞了！
期待您的“紙小墨寫作工具”哦～
最好有个“生成文件头”的快捷键，把这些 title 啊，author 啊什么的，都自动生成哈 ^__^
