### ISSUE TITLE
请问可否实现自定义 image 尺寸的功能呢？

### ISSUE THREAD

**Issue by hiweed** [InkProject/ink#85]
请问可否实现自定义图片尺寸的功能呢？
实在不想在 markdown 里使用 html 的 img src 标签。

请参考这里：https://gist.github.com/uupaa/f77d2bcf4dc7a294d109

个人比较倾向于这种语法：
```
![](-images/image.png | width=100)
```

P.S. 
Markdown 有这么多种方言，还真不如 Asciidoc 标准那么统一。

**Comment by imeoer** [comment]
@hiweed 目前暂时不支持这种方言哈。

**Comment by hiweed** [comment]
好的，谢谢回复，理解。 :-)
