### ISSUE TITLE
[bug]  preview 的效果和 html 不同，缺少 highlightjs 添加的 css 标签

### ISSUE THREAD

**Issue by fofen** [InkProject/ink#90]
## bug 重现步骤
1. 键入 `./ink preview` 命令
2. 用 Chrome 浏览器访问 `localhost:8000`，预览文章 `20171028.html `
3. 引文部分效果正常
4. 在 Chrome 中检查代码，发现 pre code 标签成功添加了 `hljs` 的 class:
```
  <pre>
    <code class="hljs yinwen">
　  <span class="hljs-comment">¹ </span>超发无上殊胜之愿……具足五劫，思惟摄取庄严佛国清净之行……于不可思议兆载永劫，积植菩萨无量德行。 <span class="hljs-comment">（63、73页）</span>
```
5. 此时，在 8000 端口仍在工作的情况下，在编辑器里打开同一篇文章 `20171028.html`，却搜不到任何 hljs 字样，对应的 html 代码如下：
```
<pre>
  <code>　¹ 超发无上殊胜之愿……具足五劫，思惟摄取庄严佛国清净之行……于不可思议兆载永劫，积植菩萨无量德行。 （63、73页）
```

---

## 我是这样发现的
我在本地修改 highlight.pack.js，调试 css， `preview` 没问题后，上传 public 到 [wenku.hongyuansi.com](wenku.hongyuansi.com)，却发现 css 没效果；然后回来查原因，才发现 preview 的 html 代码和生成的 html 文件不一样——preview 的 html 代码是正确的，而对应的 html 文件，却没有包含 hljs 的内容。

### 备注
我根据**净土宗文库**的特点，对  `highlight.pack.js` 作了修改，去掉了原有的各种语言，添加了自定义的 yinwen（引文）。
我检查了 bundle/index.js, 的确成功地打包了`highlight.pack.js`，包含了我写的 yinwen 语言定义。`preview` 能看到预期效果，证明修改的 `highlight.pack.js` 运行正常。

在执行 `preview` 命令时，有 4 行黄色的警告信息：
```
WARNING in index.js from UglifyJs
Condition always true [./~/jquery/dist/jquery.js:9778,0]
Condition always true [./source/js/highlight.pack.js:2,13]
Dropping unreachable code [./source/js/highlight.pack.js:2,55]
```
是 WARNING，不是 Error，所以打包通过。

**Comment by imeoer** [comment]
@hiweed 非常感谢报告这些问题，目前团队暂时将精力放在纸小墨项目上，我们可能会在晚些时候才能跟进这些问题了。当然，也非常欢迎你来提相关的PR。:)

**Comment by hiweed** [comment]
哈哈，好的，理解。感恩，等待……

**Comment by hiweed** [comment]
@imeoer 可以关闭这个 issue 了，这不是 bug，不好意思。

1. Markdown 解析成 HTML 文件时，是不处理 highlight 问题的；
2. Highlight 的工作，是浏览器完成的；
3. 换句话说， Highlight 的 hljs 的标签，是在浏览器中访问 html 时，浏览器执行 index.js 时才加上的；
4. 我之前遇到的问题，可能是传到 Web Server 后，由于某种原因导致 index.js 没有执行。
