### ISSUE TITLE
紙小墨 ‧ 文稿什么时候发布呀

### ISSUE THREAD

**Issue by Skyexu** [InkProject/ink#92]

**Comment by imeoer** [comment]
@Skyexu 非常感谢关注，发布时间上还没有具体确定哈，目前开发进度大约为60%。

**Comment by Skyexu** [comment]
window 真的没什么好用的 Markdown 编辑器，期待关注一波。  在 v2ex 留了邮箱的。   xkhsky@163.com

**Comment by imeoer** [comment]
@Skyexu 好的，我们届时会给所有留言邮箱发送邀请邮件的。
