### ISSUE TITLE
请增加katex支持

### ISSUE THREAD

**Issue by ossphil** [InkProject/ink#95]
希望能增加使用katex解析latex公式的功能。

**Comment by w568w** [comment]
某种意义上来说是各个主题可以自行实现的，不过得益于 Markdown 渲染库，最新版本支持将 `$ ... $` 和 `$$ ... $$` 解析为含有 MathJax 对应类名的 HTML 元素，只需要在主题的头部自行添加 MathJax 支持库即可，见 https://github.com/w568w/inkstone/commit/d25798d460952bd180b429238999c21a60f87762 。

$$\LaTeX$$


$$ 
\int_{-\infty}^\infty g(x) dx = \frac{1}{2\pi i} \oint_{\gamma} \frac{f(z)}{z-g(x)} dz
$$

**Comment by imeoer** [comment]
@w568w 赞！这个也把 PR 提出来吧
